# Generated by Django 5.0.4 on 2024-04-26 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='modified_at',
            new_name='modefied_at',
        ),
    ]
