# Generated by Django 5.0.4 on 2024-04-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='modefied_at',
            new_name='modified_at',
        ),
    ]
